version: "3.8"
services:
    db:
        image: yobasystems/alpine-mariadb:10.4.17
        container_name: db_courssymfony
        restart: no
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: pass123
        ports:
            - '3306:3306'
        networks:
            - dev
    maildev:
        image: djfarrelly/maildev
        container_name: maildev_courssymfony
        restart: no
        ports:
            - '1080:80'
            - '1025:25'
        networks:
            - dev

networks:
    dev:

volumes:
    db-data: